steps:
  # 1. Build Inteligente com Kaniko (Substitui pull, build e push do Docker)
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/$PROJECT_ID/xmlrsus2:latest'
      - '--cache=true'
      - '--cache-ttl=168h' # Guarda o cache das dependências por 7 dias!

  # 2. Deploy para Cloud Run Service (A API Barata e Rápida)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'xmlrsus2'
      - '--image=gcr.io/$PROJECT_ID/xmlrsus2:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--memory=1Gi' # Reduzido para 1Gi (A API não precisa de mais que isso)
      - '--cpu=1'
      - '--concurrency=80'
      - '--timeout=1800'
      - '--execution-environment=gen2'
      # NOTA: A flag --no-cpu-throttling foi removida definitivamente para zerar o custo ocioso.

  # 3. Deploy para Cloud Run Jobs (O Robô Pesado)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'gax-worker-job'
      - '--image=gcr.io/$PROJECT_ID/xmlrsus2:latest'
      - '--region=us-central1'

options:
  logging: CLOUD_LOGGING_ONLY