steps:
  # 1. Build Inteligente com Kaniko (Substitui pull, build e push do Docker)
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/$PROJECT_ID/xmlrsus2:latest'
      - '--cache=true'
      - '--cache-ttl=168h' # Guarda o cache das dependências por 7 dias!

  # 2. Deploy para Cloud Run (Blindado com as otimizações de performance)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'xmlrsus2'
      - '--image=gcr.io/$PROJECT_ID/xmlrsus2:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--concurrency=2'
      - '--timeout=1800'
      # -- AS DUAS LINHAS ABAIXO SALVAM A PERFORMANCE DO ROBÔ --
      - '--execution-environment=gen2'
      - '--no-cpu-throttling'

options:
  logging: CLOUD_LOGGING_ONLY