# Dockerfile para o Backend FastAPI
FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./api ./api

# Expor a porta
EXPOSE 8000

# Executar a aplicação
CMD ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
